###

@host = http://localhost:5000


### Login

POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "password": "TestAdmin123!",
  "username": "testadmin"
}


### Login with wrong password

POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "password": "wrongpassword",
  "username": "admin"
}


### Login with unknown user

POST {{host}}/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "password": "whatever",
  "username": "nobody"
}
