### Snapshot API Smoke Tests

@adminToken = {{loginAdmin.response.body.$.accessToken}}
@adminUserId = {{loginAdmin.response.body.$.userId}}
@baseUrl = http://localhost:5000
@nonMemberToken = {{loginNonMember.response.body.$.accessToken}}

# --- Auth ----------------------------------------------------

# @name loginAdmin

POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json
X-Correlation-Id: smoke-test-snapshot-001

{
  "password": "TestAdmin123!",
  "username": "testadmin"
}


###

# @name loginNonMember

POST {{baseUrl}}/api/auth/login HTTP/1.1
Content-Type: application/json
X-Correlation-Id: smoke-test-snapshot-002

{
  "password": "NonMember123!",
  "username": "nonmember"
}


###

# --- Project Setup -------------------------------------------

# @name createProject

POST {{baseUrl}}/api/projects HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{adminToken}}
X-Correlation-Id: smoke-test-snapshot-003

{
  "description": "Project for snapshot smoke test",
  "gitProvider": "github",
  "gitRemoteUrl": "https://github.com/test/test.git",
  "name": "Snapshot Smoke Test Project"
}


###

# @name addMember

POST {{baseUrl}}/api/projects/{{createProject.response.body.$.id}}/members HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{adminToken}}
X-Correlation-Id: smoke-test-snapshot-004

{
  "role": "Member",
  "userId": "{{adminUserId}}"
}


###

# @name addColumn

POST {{baseUrl}}/api/projects/{{createProject.response.body.$.id}}/columns HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{adminToken}}
X-Correlation-Id: smoke-test-snapshot-005

{
  "name": "Backlog",
  "position": 0,
  "wipLimit": null
}


###

# --- Snapshot Tests -------------------------------------------


### Get snapshot as project member (should be 200 OK)

GET {{baseUrl}}/api/projects/{{createProject.response.body.$.id}}/ProjectSnapshot HTTP/1.1
Authorization: Bearer {{adminToken}}
Content-Type: application/json
X-Correlation-Id: smoke-test-snapshot-006


###


### Get snapshot as non-member (should be 403 Forbidden)

GET {{baseUrl}}/api/projects/{{createProject.response.body.$.id}}/ProjectSnapshot HTTP/1.1
Authorization: Bearer {{nonMemberToken}}
Content-Type: application/json
X-Correlation-Id: smoke-test-snapshot-007


###


### Get snapshot for non-existent project (should be 403 Forbidden)

GET {{baseUrl}}/api/projects/00000000-0000-0000-0000-000000000000/ProjectSnapshot HTTP/1.1
Authorization: Bearer {{adminToken}}
Content-Type: application/json
X-Correlation-Id: smoke-test-snapshot-008


###


### Get snapshot without token (should be 401 Unauthorized)

GET {{baseUrl}}/api/projects/{{createProject.response.body.$.id}}/ProjectSnapshot HTTP/1.1
Content-Type: application/json
X-Correlation-Id: smoke-test-snapshot-009


###

# --- Cleanup -------------------------------------------------

POST {{baseUrl}}/api/projects/{{createProject.response.body.$.id}}/toggle-archive HTTP/1.1
Authorization: Bearer {{adminToken}}
X-Correlation-Id: smoke-test-snapshot-010
